export const TONES = [
    "Tone",
    "Analytical",
    "Assertive",
    "Authoritative",
    "Challenging",
    "Conversational",
    "Curious",
    "Educational",
    "Empathetic",
    "Friendly",
    "Funny",
    "Happy",
    "Informative",
    "Inspirational",
    "Metaphorical",
    "Motivational",
    "Narrative",
    "Normal",
    "Persuasive",
    "Philosophical",
    "Professional",
    "Reflective",
    "Sarcastic",
    "Sincere",
    "Visionary",
    "Whimsical"
];

export const LANGUAGES = [
    "Language",
    "English",
    "Spanish",
    "French",
    "German",
    "Italian", // Add more languages as needed
    "Hindi"
];

export const COMMENT_MOTIVES = [
    "Address Concerns",
    "Address Misconceptions",
    "Ask Questions",
    "Build Rapport",
    "Build Relationships",
    "Encourage Action",
    "Encourage Debate",
    "Encourage Engagement",
    "Encourage Sharing",
    "Establish Expertise",
    "Highlight Author",
    "Highlight Partnerships",
    "Offer Support",
    "Offer Tips",
    "Promote Product",
    "Provide Feedback",
    "Provide Resources",
];
export const POSTING_MOTIVES = [
    "Motive",
    "Celebrating Others",
    "Challenges and Solutions",
    "Common Myths",
    "Company Updates",
    "Educational",
    "Encourage Engagement",
    "Informational",
    "Introduction Post",
    "Networking",
    "Personal Story",
    "Poll",
    "Promotional",
    "Provide Value",
    "Seeking Advice",
    "Success Stories",
    "Thought Leadership",
];