export const LINKEDIN_CLASS_NAMES = {
    DATA_QL_EDITOR_CONTENT_EDITABLE: "data-test-ql-editor-contenteditable",
    COMMENT_BOX_FORM: "comments-comment-box__form",
    COMMENT_TEXTEDITOR: "comments-comment-texteditor",
    EDITOR_CONTAINER: "editor-container",
    COMMENT_BOX_CR: "comments-comment-box--cr",
    AUTHOR_NAME: "update-components-actor__title",
    AUTHOR_SPAN: "span[dir='ltr'] > span:not([aria-hidden])",
    POST_EDITOR: "ql-editor",
    CREATE_POST_MODAL: "share-creation-state__footer",
    SHARE_CREATION_FOOTER: "share-creation-state__footer",
    COMMENTS_COMMENT_ITEM: ".comments-comment-item",
    COMMENTS_POST_META_H3_SPAN_COMMENTS__TEXT: ".comments-post-meta h3 span.comments-post-meta__name-text",
    DIV_COMMENTS_COMMENT_ITEM_SHOW_MORE_TEXT: "div.comments-comment-item__inline-show-more-text",
    COMMENTS_SOCIAL_ACTIVITY_COMMENTS_REPLIES_LIST: ".comment-social-activity .comments-replies-list",
    COMMENTS_COMMENT_META_DESCRIPTION_TITLE: 'comments-comment-meta__description-title',
    COMMENTS_THREAD_ENTITY: ".comments-thread-entity",
    COMMENTS_COMMENT_META_ACTOR: 'comments-comment-meta__actor',
    COMMENTS_COMMENT_CONTENT_ELEMENT: "comments-comment-item__inline-show-more-text",
    COMMENTS_REPLIES_LIST: ".comments-replies-list",
    OCCLUDABLE_UPDATE: "occludable-update",
    RELATIVE: "relative",
    ENTITY_RESULT_CONTENT_SUMMARY: "entity-result__content-summary--3-lines",
    EMBER_VIEW: "ember-view",
    UPDATE_OUTLET: "update-outlet",
    COMMENT_BOX_FORM_CONTAINER: "comments-comment-box__form-container",
    COMMENT_BOX_FORM_CONTAINER2: "comments-comment-box__form",
    POST_POPUP_CONTAINER_CLASS: "feed-shared-update-detail-viewer__content",
    ENTITY_RESULT__CONTENT_CONTAINER: "entity-result__content-container",
    UPDATE_RESULT__CONTENT_CONTAINER: "update-components__content-container",
    POST_TEXT_OUTER_CONTAINER: "feed-shared-update-v2__description-wrapper",
    POST_TEXT_SPAN_CONTAINER: "break-words",
    COMMENTS_HIGHLIGHTED_COMMENT_ITEM: "comments-highlighted-comment-item",
    COMMENTS_COMMENT_ITEM_HIGHLIGHTED: "comments-comment-item--highlighted",
    COMMENTS_COMMENT_ITEM_CONTENT_BODY: "comments-comment-item-content-body",
    COMMENTS_HIGHLIGHTED_COMMENT_ITEM_CONTENT_BODY:
        "comments-highlighted-comment-item-content-body",
    COMMENTS_COMMENT_ITEM_SPAN_CONTAINER: "comments-comment-item__main-content",
    COMMENT_COMMENT_ITEM_POST_META: "comments-comment-item__post-meta",
    COMMENT_POST_META_NAME_TEXT_SPAN_CONTAINER: "comments-post-meta__name-text",
    COMMENTS_COMMENT_MAIN_ELEMENT: "comments-comment-entity",
    PROFILE_CREATOR__CONTENT_CONTAINER: "profile-creator-shared-feed-update__container",
    AUTHOR_NAME_CONTAINER: "update-components-actor__name",
    ENTITY_RESULT__CONTENT_TITLE: "entity-result__title-text",
    UPDATE_RESULT__CONTENT_TITLE: "update-components-actor__name",
    COMMENT_BOX_TEXT_EDITOR: "comments-comment-box-comment__text-editor",
    COMMENT_BOX_WITH_ID: "comments-comment-box",
    COMMENT_BOX_WITH_ID2: "comments-comment-box--cr",
    COMMENT_EDITOR: "ql-editor",
    ART_DECO_CARD: "artdeco-card",
    COMMENTS_COMMENT_ENTITY: ".comments-comment-entity",
    FIE_IMPRESSION_CONTAINER: "fie-impression-container",
    MESSAGE_BOX_CONTAINER: "msg-form__msg-content-container",
    MESSAGE_FORM_FOOTER: "msg-form__footer",
    MESSAGE_FORM: "msg-form",
    MESSAGE_THREAD_CONTAINER: "msg-s-message-list-content",
    MESSAGE_TEXT_LIST_ITEM: "msg-s-message-list__event",
    MESSAGE_TEXT_FROM_USER: "msg-s-message-group__name",
    MESSAGE_TEXT_CONTENT: "msg-s-event__content",
    MESSAGE_OVERLAY_CONVERSATION_BUBBLE: "msg-overlay-conversation-bubble",
    MESSAGE_OVERLAY_CONVERSATION_BUBBLE_HEADER: "msg-overlay-conversation-bubble_header",
    MESSAGE_EDITOR: "msg-form__contenteditable",
    ME_MENU_TRIGGER: "global-nav__primary-link-me-menu-trigger",
    ME_MENU_ITEMS_CONTAINER: "global-nav__me-content, .artdeco-dropdown__content.artdeco-dropdown__content--is-open",
    ART_DECO_ENTITY_LOCKUP__TITLE  : "artdeco-entity-lockup__title"
}

export const LINKEDIN_ID_NAMES = {
    MESSAGE_THREAD_OTHER_USER: "thread-detail-jump-target",
    EXPERIENCE_DIV_ID: "experience",
    PROFILE_EDIT_FORM_PAGE_HEADER: "profile-edit-form-page-header",
    EDUCATION_DIV_ID: "education",
    LICENSES_AND_CERTIFICATIONS_DIV_ID: "licenses_and_certifications",
    PROFILE_URL: "ember687",
    RECOMMENDATION_TEXT_AREA:
        "multiline-text-form-component-profileEditFormElement-WRITE-RECOMMENDATION-recommendation-11-recommendationText",
};



export const LOCAL_STORAGE_NAMES = {
    LINKEDIN_USERNAME: "linkedInUserName",
    LINKEDIN_PROFILE_URL : "linkedInProfileUrl", 
}